version: '3.7'

services:
  depa-testing-database:
    image: mongo:4.0-xenial
    volumes:
      - ./mongo/fixtures/initDB.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017

  depa-testing-api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./src:/app/src
    command: mvn spring-boot:run
    ports:
      - 8080:8080
    environment:
      - GOOGLE_ID
      - GOOGLE_SECRET
      - FACEBOOK_ID
      - FACEBOOK_SECRET
      - SPRING_DATA_MONGODB_HOST=depa-testing-database
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - depa-testing-database 
